Fixes Issue #2.
DB Schema:

* Switched all string fields which always have the same length from VARCHAR to CHAR. In fact, most string fields are like that
* Minimized string field length when one can determine no higher length will be needed (the fixed-length fields, US state names etc.)
* Using BOOLEAN where possible
* Made some fields integral again which before were strings because of there being decimal-notation data in the CSVs - depsite it always having a .00 suffix
* Tweaked some integer sizes

Benchmark queries:

* Corrected a column name in Q8
* Generated results for queries Q1-Q9 using the data for years 2000-2008 inclusive

DB setup script:

* Now preferring null'ing a field rather than setting a baseless default value (e.g. we null tail numbers which have even one invalid character if we can't determine with certainty which airline it was.
* Fixed a bug with the function detecting whether a DB is currently up
* Tweaked printed messages
* Tweaked variable names
* Ensured the DB exists check is sent to the right server
* Reflected the schema changes in the schema cretain const here
* Fixed an off-by-1 bug in the iteration of calenar years when loading data (we were skipping the year-before-last in many cases)

Other changes:

* Added some utility scripts and made various modifications to existing ones
* Added some entries to the ignore files
* Made .gitignore the main ignore file and having .hgignore link to it

diff --git a/setup-usdt-ontime-db b/setup-usdt-ontime-db
--- a/setup-usdt-ontime-db
+++ b/setup-usdt-ontime-db
@@ -48,7 +48,7 @@ estimated_data_per_month_mb=200
 download_dir="$PWD/usdt-ontime-downloads"
 db_name="usdt-ontime"
 table_name="ontime"
-db_farm_port=50000
+port=50000
 empty_as_null=1 # NOT NULL'ing columns is currently unsupported due to trouble with missing integer values
 hostname=localhost
 mask_unexpected_chars=1 # Some string fields have non-ASCII characters, obviouslly erroneous
@@ -74,8 +74,7 @@ function usage {
 	echo "  -d, --db-name NAME       Name of the database holding on-time performance data"
 	echo "  -f, --db-farm PATH       Filesystem path for the root directory of the MonetDB"
 	echo "                           database farm in which to place the database"
-	echo "  -p, --port NUMBER        Network port on the local host, which the server"
-	echo "                           will related to the DB farm"
+	echo "  -p, --port NUMBER        IP port on which to connect to the database"
 	echo "  -k, --keep-downloads     Keep the zipped CSV files downloaded from the US department"
 	echo "                           of transport's website after loading them into the DB"
 	echo "  -h, --help               Print usage information"
@@ -130,13 +129,10 @@ function db_farm_is_up {
 function db_is_up {
 	# This assumes the DB exists
 	local db_name=$1
-	local port=$2
 	[[ "$be_verbose" ]] && echo monetdb -p $port status $db_name
-	local monetdb_status_output=$(monetdb -p $port status $db_name 2>/dev/null )
-	(( $(echo $monetdb_status_output | wc -l) > 0 )) || return 1
-	status=$(echo $monetdb_status_output | tail -1 | sed -r 's/^'$db_name'\s*([^ ]*).*$/\1/;')
+	status=$(monetdb -p $port status $db_name 2>/dev/null | tail -1 | sed -r 's/^'$db_name'\s*([^ ]*).*$/\1/;')
 	[[ "$be_verbose" ]] && echo "Database $db_name is" $(echo $status | sed 's/R/running/; s/S/not running/; s/^$/not running/')
-	[[ $status == "R" ]]
+	[[ -n "$status" && $status == "R" ]] && return 0 || return 1
 }
 
 function db_exists {
@@ -150,10 +146,10 @@ function run_mclient {
 #	local db_name="$1"
 	local query="$1"
 	local format="${2:-csv}"
-#	local db_farm_port="$4"
+#	local port="$4"
 #	local hostname="$5"
-	[[ $be_verbose ]] && echo "mclient -lsql -f $format -d $db_name -p $db_farm_port -h $hostname -s \"$query\""
-	mclient -lsql -f $format -d $db_name -p $db_farm_port -h $hostname -s "$query" > /dev/null
+	[[ $be_verbose ]] && echo "mclient -lsql -f $format -d $db_name -p $port -h $hostname -s \"$query\""
+	mclient -lsql -f $format -d $db_name -p $port -h $hostname -s "$query" > /dev/null
 }
 
 function is_number {
@@ -169,13 +165,13 @@ function get_and_load_month_data {
 	local csv_file="${zip_file/zip/csv}"
 	local quiet_switch=""
 	local char_masking_sed_command
-	[[ "$mask_unexpected_chars" ]] && char_masking_sed_command=' s/[\xE0-\xEF]/_/g;'
+	[[ "$mask_unexpected_chars" ]] && char_masking_sed_command='s/,[^,]*[\xE0-\xEF][^,]*,/,,/;'
 	[[ "$be_verbose" ]] && quiet_switch="-q"
 	pushd $download_dir > /dev/null
 	[[ "$be_verbose" ]] && echo "wget -c \"${url_prefix}${zip_file}\""
 	wget -c $quiet_switch "${url_prefix}${zip_file}"
-	[[ "$be_verbose" ]] && echo "unzip -p -o \"$zip_file\" \"$csv_file\" | LC_ALL=C sed 's/\xE4NKNO\xE6/UNKNOW/;'${char_masking_sed_command} > \"$csv_file\""
-	unzip -p $quiet_switch -o "$zip_file" "$csv_file" | LC_ALL=C sed 's/\xE4NKNO\xE6/UNKNOW/;'"${char_masking_sed_command}" > "$csv_file"
+	[[ "$be_verbose" ]] && echo "unzip -p -o \"$zip_file\" \"$csv_file\" | LC_ALL=C sed 's/\.00,/,/g; s/\xE4NKNO\xE6/UNKNOW/;'${char_masking_sed_command} > \"$csv_file\""
+	unzip -p $quiet_switch -o "$zip_file" "$csv_file" | LC_ALL=C sed -r 's/\.00,/,/g; s/\xE4NKNO\xE6/UNKNOW/;'"${char_masking_sed_command}" > "$csv_file"
 
 	[[ "$empty_as_null" ]] && null_as_clause=" NULL AS ''"
 	# Note: For MonetDB, the OFFSET value in COPY INTO statements 
@@ -189,7 +185,7 @@ function get_and_load_month_data {
 
 #------------------------------
 
-schema_creation_sql='CREATE TABLE ontime ( Year_ INT NOT NULL, Quarter TINYINT NOT NULL, Month_ TINYINT NOT NULL, DayofMonth TINYINT NOT NULL, DayOfWeek TINYINT NOT NULL, FlightDate DATE NOT NULL, UniqueCarrier VARCHAR(7) NOT NULL, AirlineID INT NOT NULL, Carrier VARCHAR(2) NOT NULL, TailNum VARCHAR(50) DEFAULT NULL, FlightNum VARCHAR(10) NOT NULL, OriginAirportID INT DEFAULT NULL, OriginAirportSeqID INT NOT NULL, OriginCityMarketID INT NOT NULL, Origin VARCHAR(5) NOT NULL, OriginCityName VARCHAR(100) NOT NULL, OriginState VARCHAR(2) DEFAULT NULL, OriginStateFips VARCHAR(10) DEFAULT NULL, OriginStateName VARCHAR(100) DEFAULT NULL, OriginWac INT NOT NULL, DestAirportID INT NOT NULL, DestAirportSeqID INT NOT NULL, DestCityMarketID INT NOT NULL, Dest VARCHAR(5) NOT NULL, DestCityName VARCHAR(100) NOT NULL, DestState VARCHAR(2) DEFAULT NULL, DestStateFips VARCHAR(10) DEFAULT NULL, DestStateName VARCHAR(100) DEFAULT NULL, DestWac INT NOT NULL, CRSDepTime INT NOT NULL, DepTime INT DEFAULT NULL, DepDelay INT DEFAULT NULL, DepDelayMinutes INT DEFAULT NULL, DepDel15 INT DEFAULT NULL, DepartureDelayGroups INT DEFAULT NULL, DepTimeBlk VARCHAR(20) NOT NULL, TaxiOut INT DEFAULT NULL, WheelsOff INT DEFAULT NULL, WheelsOn INT DEFAULT NULL, TaxiIn INT DEFAULT NULL, CRSArrTime INT NOT NULL, ArrTime INT DEFAULT NULL, ArrDelay INT DEFAULT NULL, ArrDelayMinutes INT DEFAULT NULL, ArrDel15 INT DEFAULT NULL, ArrivalDelayGroups INT DEFAULT NULL, ArrTimeBlk VARCHAR(20) NOT NULL, Cancelled TINYINT NOT NULL, CancellationCode VARCHAR(1) DEFAULT NULL, Diverted TINYINT NOT NULL, CRSElapsedTime INT DEFAULT NULL, ActualElapsedTime INT DEFAULT NULL, AirTime INT DEFAULT NULL, Flights INT NOT NULL, Distance INT NOT NULL, DistanceGroup TINYINT NOT NULL, CarrierDelay INT DEFAULT NULL, WeatherDelay INT DEFAULT NULL, NASDelay INT DEFAULT NULL, SecurityDelay INT DEFAULT NULL, LateAircraftDelay INT DEFAULT NULL, FirstDepTime VARCHAR(10) DEFAULT NULL, TotalAddGTime VARCHAR(10) DEFAULT NULL, LongestAddGTime VARCHAR(10) DEFAULT NULL, DivAirportLandings VARCHAR(10) DEFAULT NULL, DivReachedDest VARCHAR(10) DEFAULT NULL, DivActualElapsedTime VARCHAR(10) DEFAULT NULL, DivArrDelay VARCHAR(10) DEFAULT NULL, DivDistance VARCHAR(10) DEFAULT NULL, Div1Airport VARCHAR(10) DEFAULT NULL, Div1AirportID INT DEFAULT NULL, Div1AirportSeqID INT DEFAULT NULL, Div1WheelsOn VARCHAR(10) DEFAULT NULL, Div1TotalGTime VARCHAR(10) DEFAULT NULL, Div1LongestGTime VARCHAR(10) DEFAULT NULL, Div1WheelsOff VARCHAR(10) DEFAULT NULL, Div1TailNum VARCHAR(10) DEFAULT NULL, Div2Airport VARCHAR(10) DEFAULT NULL, Div2AirportID INT DEFAULT NULL, Div2AirportSeqID INT DEFAULT NULL, Div2WheelsOn VARCHAR(10) DEFAULT NULL, Div2TotalGTime VARCHAR(10) DEFAULT NULL, Div2LongestGTime VARCHAR(10) DEFAULT NULL, Div2WheelsOff VARCHAR(10) DEFAULT NULL, Div2TailNum VARCHAR(10) DEFAULT NULL, Div3Airport VARCHAR(10) DEFAULT NULL, Div3AirportID INT DEFAULT NULL, Div3AirportSeqID INT DEFAULT NULL, Div3WheelsOn VARCHAR(10) DEFAULT NULL, Div3TotalGTime VARCHAR(10) DEFAULT NULL, Div3LongestGTime VARCHAR(10) DEFAULT NULL, Div3WheelsOff VARCHAR(10) DEFAULT NULL, Div3TailNum VARCHAR(10) DEFAULT NULL, Div4Airport VARCHAR(10) DEFAULT NULL, Div4AirportID INT DEFAULT NULL, Div4AirportSeqID INT DEFAULT NULL, Div4WheelsOn VARCHAR(10) DEFAULT NULL, Div4TotalGTime VARCHAR(10) DEFAULT NULL, Div4LongestGTime VARCHAR(10) DEFAULT NULL, Div4WheelsOff VARCHAR(10) DEFAULT NULL, Div4TailNum VARCHAR(10) DEFAULT NULL, Div5Airport VARCHAR(10) DEFAULT NULL, Div5AirportID INT DEFAULT NULL, Div5AirportSeqID INT DEFAULT NULL, Div5WheelsOn VARCHAR(10) DEFAULT NULL, Div5TotalGTime VARCHAR(10) DEFAULT NULL, Div5LongestGTime VARCHAR(10) DEFAULT NULL, Div5WheelsOff VARCHAR(10) DEFAULT NULL, Div5TailNum VARCHAR(10) DEFAULT NULL ); '
+schema_creation_sql='CREATE TABLE ontime ( Year_ INT NOT NULL, Quarter TINYINT NOT NULL, Month_ TINYINT NOT NULL, DayofMonth TINYINT NOT NULL, DayOfWeek TINYINT NOT NULL, FlightDate DATE NOT NULL, UniqueCarrier CHAR(2) NOT NULL, AirlineID INT NOT NULL, Carrier CHAR(2) NOT NULL, TailNum VARCHAR(6) DEFAULT NULL, FlightNum VARCHAR(4) NOT NULL, OriginAirportID INT NOT NULL, OriginAirportSeqID INT NOT NULL, OriginCityMarketID INT NOT NULL, Origin CHAR(3) NOT NULL, OriginCityName VARCHAR(40) NOT NULL, OriginState CHAR(2) DEFAULT NULL, OriginStateFips CHAR(2) DEFAULT NULL, OriginStateName VARCHAR(19) DEFAULT NULL, OriginWac INT NOT NULL, DestAirportID INT NOT NULL, DestAirportSeqID INT NOT NULL, DestCityMarketID INT NOT NULL, Dest CHAR(3) NOT NULL, DestCityName VARCHAR(40) NOT NULL, DestState CHAR(2) DEFAULT NULL, DestStateFips CHAR(2) DEFAULT NULL, DestStateName VARCHAR(19) DEFAULT NULL, DestWac INT NOT NULL, CRSDepTime INT NOT NULL, DepTime INT DEFAULT NULL, DepDelay INT DEFAULT NULL, DepDelayMinutes INT DEFAULT NULL, DepDel15 INT DEFAULT NULL, DepartureDelayGroups TINYINT DEFAULT NULL, DepTimeBlk CHAR(9) NOT NULL, TaxiOut INT DEFAULT NULL, WheelsOff CHAR(4) DEFAULT NULL, WheelsOn CHAR(4) DEFAULT NULL, TaxiIn INT DEFAULT NULL, CRSArrTime CHAR(4) DEFAULT NULL, ArrTime CHAR(4) DEFAULT NULL, ArrDelay INT DEFAULT NULL, ArrDelayMinutes INT DEFAULT NULL, ArrDel15 INT DEFAULT NULL, ArrivalDelayGroups INT DEFAULT NULL, ArrTimeBlk CHAR(9) NOT NULL, Cancelled BOOLEAN NOT NULL, CancellationCode CHAR(1) DEFAULT NULL, Diverted BOOLEAN NOT NULL, CRSElapsedTime INT DEFAULT NULL, ActualElapsedTime INT DEFAULT NULL, AirTime INT DEFAULT NULL, Flights INT NOT NULL, Distance INT NOT NULL, DistanceGroup TINYINT NOT NULL, CarrierDelay INT DEFAULT NULL, WeatherDelay INT DEFAULT NULL, NASDelay INT DEFAULT NULL, SecurityDelay INT DEFAULT NULL, LateAircraftDelay INT DEFAULT NULL, FirstDepTime CHAR(4) DEFAULT NULL, TotalAddGTime SMALLINT DEFAULT NULL, LongestAddGTime SMALLINT DEFAULT NULL, DivAirportLandings CHAR(1) DEFAULT NULL, DivReachedDest CHAR(4) DEFAULT NULL, DivActualElapsedTime SMALLINT DEFAULT NULL, DivArrDelay SMALLINT DEFAULT NULL, DivDistance SMALLINT DEFAULT NULL, Div1Airport CHAR(3) DEFAULT NULL, Div1AirportID INT DEFAULT NULL, Div1AirportSeqID INT DEFAULT NULL, Div1WheelsOn CHAR(4) DEFAULT NULL, Div1TotalGTime SMALLINT DEFAULT NULL, Div1LongestGTime SMALLINT DEFAULT NULL, Div1WheelsOff CHAR(4) DEFAULT NULL, Div1TailNum VARCHAR(6) DEFAULT NULL, Div2Airport CHAR(3) DEFAULT NULL, Div2AirportID INT DEFAULT NULL, Div2AirportSeqID INT DEFAULT NULL, Div2WheelsOn CHAR(4) DEFAULT NULL, Div2TotalGTime SMALLINT DEFAULT NULL, Div2LongestGTime SMALLINT DEFAULT NULL, Div2WheelsOff CHAR(4) DEFAULT NULL, Div2TailNum VARCHAR(6) DEFAULT NULL, Div3Airport CHAR(3) DEFAULT NULL, Div3AirportID INT DEFAULT NULL, Div3AirportSeqID INT DEFAULT NULL, Div3WheelsOn CHAR(4) DEFAULT NULL, Div3TotalGTime SMALLINT DEFAULT NULL, Div3LongestGTime SMALLINT DEFAULT NULL, Div3WheelsOff CHAR(4) DEFAULT NULL, Div3TailNum VARCHAR(6) DEFAULT NULL, Div4Airport CHAR(3) DEFAULT NULL, Div4AirportID INT DEFAULT NULL, Div4AirportSeqID INT DEFAULT NULL, Div4WheelsOn CHAR(4) DEFAULT NULL, Div4TotalGTime SMALLINT DEFAULT NULL, Div4LongestGTime SMALLINT DEFAULT NULL, Div4WheelsOff CHAR(10) DEFAULT NULL, Div4TailNum VARCHAR(6) DEFAULT NULL, Div5Airport CHAR(3) DEFAULT NULL, Div5AirportID INT DEFAULT NULL, Div5AirportSeqID INT DEFAULT NULL, Div5WheelsOn CHAR(4) DEFAULT NULL, Div5TotalGTime SMALLINT DEFAULT NULL, Div5LongestGTime SMALLINT DEFAULT NULL, Div5WheelsOff CHAR(4) DEFAULT NULL, Div5TailNum VARCHAR(6) DEFAULT NULL );'
 
 
 #------------------------------
@@ -238,9 +234,9 @@ while [[ $# > 0 ]]; do
 		shift # past argument
 		;;
 	-p|--port|--dbfarm-port)
-		db_farm_port="$2"
+		port="$2"
 		shift # past argument
-		is_positive_int $db_farm_port || die "Invalid DB farm port $db_farm_port"
+		is_positive_int $port || die "Invalid DB farm port $port"
 		;;
 	-D|--download-to|--download-dir|-dl-dir|--download-directory)
 		download_dir="$2"
@@ -318,14 +314,14 @@ die "Not enough disk space at $db_farm to load the data: We need ${necessary_spa
 # Ensure we have a DB farm that's up in which to create the database - or try to create it
 
 if db_farm_exists $db_farm; then
-	db_farm_port=$(property_of_dbfarm "port" $db_farm)
+	port=$(property_of_dbfarm "port" $db_farm)
 	db_farm_is_up $db_farm || monetdbd start $db_farm || die "Could not start the DB farm at $db_farm"
 else
 	[[ "$be_verbose" ]] && echo "monetdbd create $db_farm" 
 	monetdbd create $db_farm || die "A MonetDB database farm does not exist at ${db_farm}, and cannot be created there."
-	[[ -z $db_farm_port ]] || db_farm_port=50002
-	[[ "$be_verbose" ]] && echo "monetdbd set port=$db_farm_port $db_farm"
-	monetdbd set port=$db_farm_port $db_farm || die "Can't set the daemon port for new DB farm ${db_farm} to ${db_farm_port}."
+	[[ -z $port ]] || port=50002
+	[[ "$be_verbose" ]] && echo "monetdbd set port=$port $db_farm"
+	monetdbd set port=$port $db_farm || die "Can't set the daemon port for new DB farm ${db_farm} to ${port}."
 	[[ "$be_verbose" ]] && echo "monetdbd start $db_farm"
 	monetdbd start $db_farm || die 
 fi
@@ -334,14 +330,14 @@ db_farm_is_up $db_farm || die "Could not get DB farm at $db_farm to the started 
 
 # So, do we actually need to create anything?
 
-if db_exists "$db_name" "$db_farm_port"; then
+if db_exists "$db_name" "$port"; then
 	if db_is_up "$db_name"; then
-		[[ "$be_verbose" ]] &&  echo "monetdb -p $db_farm_port stop $db_name"
-		monetdb -p $db_farm_port stop $db_name  >/dev/null || die "Can't stop the existing DB named $db_name in DB farm $db_farm." 
+		[[ "$be_verbose" ]] &&  echo "monetdb -p $port stop $db_name"
+		monetdb -p $port stop $db_name  >/dev/null || die "Can't stop the existing DB named $db_name in DB farm $db_farm." 
 	fi
 	if [[ "$recreate_db" ]]; then 
-		[[ "$be_verbose" ]] &&  echo "monetdb -p $db_farm_port destroy -f $db_name" 
-		monetdb -p $db_farm_port destroy -f $db_name >/dev/null || die "Failed destroying the existing DB named $db_name in DB farm $db_farm."
+		[[ "$be_verbose" ]] &&  echo "monetdb -p $port destroy -f $db_name" 
+		monetdb -p $port destroy -f $db_name >/dev/null || die "Failed destroying the existing DB named $db_name in DB farm $db_farm."
 		need_to_create_the_db=1
 	elif [[ ! "$append_to_db" ]]; then
 		die "A database named $db_name already exists in DB farm ${db_farm}, so giving up. Perhaps you wanted to recreate it or append to it?"
@@ -354,8 +350,8 @@ fi
 
 if [[ "$need_to_create_the_db" ]]; then
 	( 
-	( [[ "$be_verbose" ]] && echo "monetdb -p $db_farm_port create $db_name" ; monetdb -p $db_farm_port create $db_name > /dev/null ) &&  
-	( [[ "$be_verbose" ]] && echo "monetdb -p $db_farm_port release $db_name" ;  monetdb -p $db_farm_port release $db_name > /dev/null ) 
+	( [[ "$be_verbose" ]] && echo "monetdb -p $port create $db_name" ; monetdb -p $port create $db_name > /dev/null ) &&  
+	( [[ "$be_verbose" ]] && echo "monetdb -p $port release $db_name" ;  monetdb -p $port release $db_name > /dev/null ) 
 	) || die "Failed to create (and release) a database named $db_name in DB farm $db_farm for US Deptartment of Transport on-time performance data."
 	[[ $empty_as_null ]] || schema_creation_sql=$(echo $schema_creation_sql | sed -r 's/INT DEFAULT NULL/INT NOT NULL DEFAULT 0/g; s/VARCHAR\(([0-9]+)\) DEFAULT NULL/VARCHAR(\1) NOT NULL DEFAULT '\'\''/g;')
 	run_mclient "$schema_creation_sql"
@@ -374,7 +370,7 @@ else
 	for ((month=${first_month};month<=12;month++)); do
 		get_and_load_month_data $first_year $month
 	done;
-	for ((year=first_year+1;year<last_year-1;year++)); do
+	for ((year=first_year+1;year<last_year;year++)); do
 		for ((month=1;month<=12;month++)); do
 			get_and_load_month_data $year $month
 		done;
